---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: team-one
  namespace: team-one-webapp
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: team-one
  sourceRef:
    kind: GitRepository
    name: team-one
