apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pagerduty-team-one-alert
  namespace: team-one-webapp
spec:
  providerRef:
    name: team-one-pagerduty
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: team-one