---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: team-two
  namespace: team-two-webapp
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fevindiaa/team-two-webapp.git