apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pagerduty-team-two-alert
  namespace: team-two-webapp
spec:
  providerRef:
    name: team-two-pagerduty
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: team-two