apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
 name: rocketchat-team-two-alert
 namespace: team-two-webapp
spec:
 providerRef:
   name: team-two-rocketchat
 eventSeverity: error
 eventSources:
   - kind: Kustomization
     name: team-two